version: '2'
volumes:
  orderer.p22network.com:
  peer0.min1.p22network.com:
  peer1.min1.p22network.com:
  peer0.min2.p22network.com:
  peer1.min2.p22network.com:

networks:
  p22network:

services:
##########################################################
  orderer.p22network.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.p22network.com
    container_name: orderer.p22network.com
    networks:
      - p22network
##########################################################
  peer0.min1.p22network.com:
    container_name: peer0.min1.p22network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.min1.p22network.com
    networks:
      - p22network
##########################################################
  peer1.min1.p22network.com:
    container_name: peer1.min1.p22network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.min1.p22network.com
    networks:
      - p22network
##########################################################
  peer0.min2.p22network.com:
    container_name: peer0.min2.p22network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.min2.p22network.com
    networks:
      - p22network
##########################################################
  peer1.min2.p22network.com:
    container_name: peer1.min2.p22network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.min2.p22network.com
    networks:
      - p22network
##########################################################
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.min1.p22network.com:7051
      - CORE_PEER_LOCALMSPID=Ministry1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/min1.p22network.com/peers/peer0.min1.p22network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/min1.p22network.com/peers/peer0.min1.p22network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/min1.p22network.com/peers/peer0.min1.p22network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/min1.p22network.com/users/Admin@min1.p22network.com/msp
      #ajouté après pour faciliter l'installation manuelle
      - CC_SRC_PATH=/opt/gopath/src/github.com/chaincode/publicAnnouncement
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/p22network.com/orderers/orderer.p22network.com/msp/tlscacerts/tlsca.p22network.com-cert.pem
      - LANGUAGE=java
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./p22ChannelArtefacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.p22network.com
      - peer0.min1.p22network.com
      - peer1.min1.p22network.com
      - peer0.min2.p22network.com
      - peer1.min2.p22network.com
    networks:
      - p22network