# Container parameters volumes and configuration
# I mounted the certificates and network artifacts on the adequate peers

version: '2'
services:
##########################################################
  orderer.p22network.com:
    container_name: orderer.p22network.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../p22ChannelArtefacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/p22network.com/orderers/orderer.p22network.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/p22network.com/orderers/orderer.p22network.com/tls/:/var/hyperledger/orderer/tls
    - orderer.p22network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
##########################################################

  peer0.min1.p22network.com:
    container_name: peer0.min1.p22network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.min1.p22network.com
      - CORE_PEER_ADDRESS=peer0.min1.p22network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.min1.p22network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.min1.p22network.com:7051
      - CORE_PEER_LOCALMSPID=Ministry1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/min1.p22network.com/peers/peer0.min1.p22network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/min1.p22network.com/peers/peer0.min1.p22network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.min1.p22network.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
##########################################################
  peer1.min1.p22network.com:
    container_name: peer1.min1.p22network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.min1.p22network.com
      - CORE_PEER_ADDRESS=peer1.min1.p22network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.min1.p22network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.min1.p22network.com:7051
      - CORE_PEER_LOCALMSPID=Ministry1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/min1.p22network.com/peers/peer1.min1.p22network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/min1.p22network.com/peers/peer1.min1.p22network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.min1.p22network.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
#########################################################
  peer0.min2.p22network.com:
    container_name: peer0.min2.p22network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.min2.p22network.com
      - CORE_PEER_ADDRESS=peer0.min2.p22network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.min2.p22network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.min2.p22network.com:7051
      - CORE_PEER_LOCALMSPID=Ministry2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/min2.p22network.com/peers/peer0.min2.p22network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/min2.p22network.com/peers/peer0.min2.p22network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.min2.p22network.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
##########################################################
  peer1.min2.p22network.com:
    container_name: peer1.min2.p22network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.min2.p22network.com
      - CORE_PEER_ADDRESS=peer1.min2.p22network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.min2.p22network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.min2.p22network.com:7051
      - CORE_PEER_LOCALMSPID=Ministry2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/min2.p22network.com/peers/peer1.min2.p22network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/min2.p22network.com/peers/peer1.min2.p22network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.min2.p22network.com:/var/hyperledger/production
    ports:  
      - 10051:7051
      - 10053:7053