NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.min1.p22network.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.min1.p22network.com-cert.pem
    OrganizationalUnitIdentifier: peer
